config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_in' => 'customers/sessions#new', as: 'new_customer_session'
    post 'customers/sign_in' => 'customers/sessions#create', as: 'customer_session'
    delete 'customers/sign_out' => 'customers/sessions#destroy', as: 'destroy_customer_session'
    get 'customers/sign_up' => 'customers/registrations#new', as: 'new_customer_registration'
    post 'customers' => 'customers/registrations#create', as: 'customer_registration'
    get 'customers/password/new' => 'customers/passwords#new', as: 'new_customer_password'
  end
  

  devise_for :admins

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end
  
  namespace :users do
    get 'homes/top'
    get 'homes/index'
    resources :shipments do
      collection do
        post :invoice
      end
    end
    resources :constructions
    resources :bodies
    resources :companies
    resources :persons
    resources :jobs
    resources :record_pdfs, only: :index
    resources :shippeds
  end

  

  root 'users/homes#index'
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :persons, dependent: :destroy
  belongs_to :user
  has_many :heads, dependent: :destroy
  has_many :construction, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :heads, dependent: :destroy
  has_many :constructions, dependent: :destroy
  has_many :companies, dependent: :destroy

  enum department: {
    honten: 0,
    kitakei: 1,
    kennan: 2,
    chikuho: 3,
    kitakyu: 4
  }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/bodies_controller.rb
class Users::BodiesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    # byebug
    @construction = Construction.find(params[:construction_id])
    @body = Body.new
    @bodies = Body.where(construction_id: params[:construction_id]).order(created_at: "ASC")
    # byebug
  end

  def create
    @body = Body.new(body_params)
    @body.save!
    redirect_to request.referer
  end

  def edit
    @body = Body.find(params[:id])
  end

  def update
    @body = Body.find(params[:id])
    @body = Body.update!(body_params)
    redirect_to users_bodies_path
  end

  def destroy
    @body = Body.find(params[:id])
    @body.destroy!
    redirect_to users_bodies_path(construction_id: @body.construction_id)
  end

  private
  def body_params
    params.require(:body).permit(
      :product_name,
      :quantity,
      :format,
      :construction_id
    )
  end
end

app/controllers/users/companies_controller.rb
class Users::CompaniesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    # byebug
    if params[:search] == nil
      if params[:key] == "supplier"
        @companies = Company.where(supplier: true)
        @company = Company.new
        @persons = Person.all
      elsif params[:key] == "user"
        @companies = Company.where(supplier: false)
        @company = Company.new
        @persons = Person.all
      elsif params[:key]
        @companies = Company.where('address LIKE ?', "%#{params[:key]}%")
        @company = Company.new
        @persons = Person.all
        # byebug
      elsif params[:id]
        @companies = Company.where(id: params[:id])
        @companies.each do |company|
          @jobs = Job.where(person_id: company.persons.ids)
        end
        @company = Company.new
        @persons = Person.all
        # byebug
      else
        @companies = Company.all
        @company = Company.new
        @persons = Person.all
        # byebug
      end
    else
      @companies = Company.where('name LIKE ?', "%#{params[:search]}%")
      @companies.each do |company|
        @jobs = Job.where(person_id: company.persons.ids)
      end
      @company = Company.new
      @persons = Person.all
      # byebug
    end
  end

  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    @company.save!
    redirect_to users_companies_path
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.user_id = current_user.id
    @company.update(company_params)
    redirect_to users_companies_path
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to users_companies_path
  end

  private
  def company_params
    params.require(:company).permit(
      :name,
      :post_code,
      :address,
      :tel,
      :fax,
      :ceo,
      :supplier,
      :user_id
    )
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/constructions_controller.rb
class Users::ConstructionsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:id] == nil
      @constructions_all = Construction.where(user_id: current_user.id)
      @constructions = @constructions_all.where(complete: false).order(company_id: "DESC")
    else
      @user_const = Construction.where(user_id: current_user.id)
      @constructions = Construction.where(company_id: params[:id]).order(complete: "ASC")
      
    end
    @bodies = Body.all
    @companies = Company.all
    @construction = Construction.new
    # byebug
  end

  def create
    @construction = Construction.new(construction_params)
    @construction.user_id = current_user.id
    @construction.complete = false
    @construction.save!
    redirect_to users_constructions_path
  end

  def edit
    @construction = Construction.find(params[:id])
    @companies = Company.all
  end

  def update
    @construction = Construction.find(params[:id])
    @construction.user_id = current_user.id
    @construction.update!(construction_params)
    redirect_to users_constructions_path
  end

  def destroy
    @construction = Construction.find(params[:id])
    @construction.destroy
    redirect_to users_constructions_path
  end

  private
  def construction_params
    params.require(:construction).permit(
      :name,
      :order_no,
      :delivery_name,
      :address,
      :person,
      :tel,
      :user_id,
      :remark,
      :company_id,
      :image,
      :image_cache,
      :complete
    )
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top
  end

  def index
    @heads = Head.all
    @constructions = Construction.all
    @companies = Company.all
    # @day_heads = Head.all
    if user_signed_in?
      @cs = Company.where(user_id: current_user.id)
      @ps = Person.where(company_id: @cs.ids)
      @jobs = Job.where(person_id: @ps.ids)
      @job_incompletes = @jobs.where(completed: "false")
      @job_pasts = @job_incompletes.where("date <= ?", Date.today - 7 )
      @job_periods = @job_pasts + @jobs.where(date: Date.today - 7 .. Date.today + 10).order(date: "DESC")
      @user_heads = Head.where(user_id: current_user.id)
      # byebug
      @day_heads = @user_heads.where(ship_date: Time.new .. Time.new + 1.week).order(ship_date: "ASC")
      @shippeds = Shipped.where(head_id: @day_heads.ids)
      @day = @user_heads.where(ship_date: Time.now.beginning_of_day .. Time.now.end_of_day)
      # byebug
    else
      @day_heads = Head.where(ship_date: Time.new - 1.day .. Time.new + 1.week)
    end
  end
  
end

app/controllers/users/jobs_controller.rb
class Users::JobsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @job = Job.new
    @person = Person.find(params[:id])
    @jobs = Job.where(person_id: @person.id).order(date: "DESC")
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to root_path
    else
      redirect_to users_jobs_path(id: @job.person_id)
    end
  end

  def edit
    @job = Job.find(params[:id])
    @person = Person.find(@job.person_id)
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:notice] = "編集できました"
    end
      redirect_to users_jobs_path(id: @job.person_id)
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to users_jobs_path(id: @job.person_id)
  end

  private
  def job_params
    params.require(:job).permit(
      :date,
      :type,
      :content,
      :person_id,
      :completed
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/persons_controller.rb
class Users::PersonsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @person = Person.new
    @company = Company.find(params[:id])
    # byebug
  end

  def index
    @person = Person.new
    @persons = Person.where(company_id: params[:id])
    @company = Company.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    @person.save!
    redirect_to users_companies_path
  end

  def edit
    @person = Person.find(params[:id])
    @company = Company.find(@person.company_id)
  end

  def update
    @person = Person.find(params[:id])
    @person.update(person_params)
    redirect_to users_companies_path
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to users_companies_path
  end

  private
  def person_params
    params.require(:person).permit(
      :name,
      :company_id,
      :handy_phone,
      :position
    )
  end
end

app/controllers/users/record_pdfs_controller.rb
class Users::RecordPdfsController < ApplicationController
  def index
    @records = Head.all # pdf上で使用するレコードのインスタンスを作成
    respond_to do |format|
      format.html
      format.pdf do

        # pdfを新規作成。インスタンスを渡す。
        pdf = RecordPdf.new(@records)

        send_data pdf.render,
          filename:    "sample.pdf",
          type:        "application/pdf",
          disposition: "inline" # 画面に表示。外すとダウンロードされる。
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/shippeds_controller.rb
class Users::ShippedsController < ApplicationController
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/bodies_helper.rb
module Users::BodiesHelper
  def qrcode
    qrcode = RQRCode::QRCode.new(
      if @construction.address == ""
        "https://www.kashiwagi-k.co.jp/"
      else
        @construction.address
      end
    )
    svg = qrcode.as_svg(
      color: "008000",
      shape_rendering: "crispEdges",
      module_size: 4,
      standalone: true,
      use_path: true
    ).html_safe
  end
end

app/helpers/users/companies_helper.rb
module Users::CompaniesHelper
end

app/helpers/users/constructions_helper.rb
module Users::ConstructionsHelper
end

app/views/users/companies/edit.html.erb
<div class="container">
  <div class="make-company m-2 p-2">
    <h4>Company Make!</h4>
    <%= form_with model:@company, url: users_company_path(@company), local: true do |f| %>
      <div class="row p-2">
        <div class="col-sm-3">
          <%= f.text_field :name, class: "form-control", placeholder: "Company name" %>
        </div>
        <div class="col-sm-2">
          <%= f.text_field :post_code, class: "form-control", placeholder: "〒" %>
        </div>
        <div class="col-sm-7">
          <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
        </div>
      </div>
      <div class="row p-2">
        <div class="col-sm-3">
          <%= f.text_field :tel, class: "form-control", placeholder: "Telephone" %>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :fax, class: "form-control", placeholder: "Fax Number" %>
        </div>
        <div class="col-sm-5">
          <%= f.text_field :ceo, class: "form-control", placeholder: "社長名" %>
        </div>
        <div class="col-sm-1">
          <%= f.check_box :supplier %>
          仕入
        </div>
      </div>
      <%= f.submit "更新", class: "btn btn-warning m-2" %>
    <% end %>
  </div>
 </div>

app/views/users/companies/index.html.erb
<div class="container">
  <div class="make-company m-2 p-2">
    <h4>Company Make!</h4>
    <%= form_with model:@company, url: users_companies_path(@company), local: true do |f| %>
      <div class="row p-2">
        <div class="col-sm-3">
          <%= f.text_field :name, class: "form-control", placeholder: "Company name" %>
        </div>
        <div class="col-sm-2">
          <%= f.text_field :post_code, class: "form-control", placeholder: "〒" %>
        </div>
        <div class="col-sm-7">
          <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
        </div>
      </div>
      <div class="row p-2">
        <div class="col-sm-3">
          <%= f.text_field :tel, class: "form-control", placeholder: "Telephone" %>
        </div>
        <div class="col-sm-3">
          <%= f.text_field :fax, class: "form-control", placeholder: "Fax Number" %>
        </div>
        <div class="col-sm-5">
          <%= f.text_field :ceo, class: "form-control", placeholder: "社長名" %>
        </div>
        <div class="col-sm-1">
          <%= f.check_box :supplier %>
          仕入
        </div>
      </div>
      <%= f.submit "登録", class: "btn btn-success m-2" %>
    <% end %>
  </div>
  <div class="company-list m-2 p-2">
    <h4>
      Company List!　
      <%= link_to "All", users_companies_path %>　
      <%= link_to "Users", users_companies_path(key: "user") %>　
      <%= link_to "Suppliers", users_companies_path(key: "supplier") %>　
      <%= link_to "久留米", users_companies_path(key: "久留米") %>　
      <%= link_to "柳川", users_companies_path(key: "柳川") %>　
      <%= link_to "城島", users_companies_path(key: "城島") %>　
      <%= link_to "大川", users_companies_path(key: "大川") %>　
      <%= link_to "大牟田", users_companies_path(key: "大牟田") %>　
      <%= link_to "三潴", users_companies_path(key: "三潴町") %>　
      <%= link_to "大木", users_companies_path(key: "大木") %>　
      <%= link_to "筑後", users_companies_path(key: "筑後") %>　
      <%= link_to "みやま", users_companies_path(key: "みやま") %>　
      <%= link_to "八女", users_companies_path(key: "八女") %>　
      <%= link_to "広川", users_companies_path(key: "広川") %>　
      <%= link_to "朝倉", users_companies_path(key: "朝倉") %>　
      <%= link_to "うきは", users_companies_path(key: "うきは") %>　
      <%= link_to "小郡", users_companies_path(key: "小郡
      ") %>　
      <%= link_to "太刀洗", users_companies_path(key: "太刀洗") %>　
    </h4>
    <div class="row row-cols-2 row-cols-md-4 g-4">
      <% @companies.each do |company| %>
        <div class="col">
          <div class="card">
            <div class="card-body border">
              <h5 class="card-title">
                <%= link_to company.name, users_companies_path(:id => company.id) %>　<%= company.ceo %>社長
                <% if company.construction.count == 0 %>
                <% else %>
                  <span class="badge bg-success rounded-pill"><%= link_to company.construction.count, users_constructions_path(:id => company.id), class: "text-white" %></span>
                <% end %>
              </h5>
              <h6 class="card-subtitle mb-2 text-muted">Tel:<%= company.tel %>　fax:<%= company.fax %></h6>
              <% @persons.where(company_id: company.id).each do |person| %>
                <% if person.position == "" %>
                  <div class="card-text m-2">
                    <% if person.handy_phone == "" %>
                      <%= link_to person.name, users_jobs_path(:id => person.id) %>さん
                    <% else %>
                      <%= link_to person.name, users_jobs_path(:id => person.id) %>さん(<%= person.handy_phone %>)
                    <% end %>
                    <% if person.jobs.count == 0 %>
                    <% else %>
                      <span class="badge bg-danger rounded-pill"><%= person.jobs.count %></span>
                    <% end %>
                  </div>
                <% else %>
                  <div class="card-text m-2">
                    <% if person.handy_phone == "" %>
                      <%= link_to person.name, users_jobs_path(:id => person.id) %><%= person.position %>
                    <% else %>
                      <%= link_to person.name, users_jobs_path(:id => person.id) %><%= person.position %>(<%= person.handy_phone %>)
                    <% end %>
                    <% if person.jobs.count == 0 %>
                    <% else %>
                      <span class="badge bg-danger rounded-pill"><%= person.jobs.count %></span>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
              <a href="<%= edit_users_company_path(company) %>" class="card-link btn btn-warning btn-sm">訂正</a>
              <a href="<%= users_persons_path(:id => company.id) %>" class="card-link btn btn-primary btn-sm">担当</a>
              <a href="<%= users_company_path(company) %>" class="card-link btn btn-danger btn-sm" data-method = "delete" >削除</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% if @jobs == nil %>
    <% else %>
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted h3">Job List</span>
        <span class="badge bg-secondary rounded-pill"><%= @jobs.count %></span>
      </h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>期限</th>
            <th>依頼</th>
            <th>内容</th>
            <th>詳細</th>
          </tr>
        </thead>
        <tbody>
          <% @jobs.each do |job| %>
            <% if job.completed == true %>
              <tr>
                <td class="text-danger">完了<%= job.updated_at.strftime('%m-%d') %></td>
                <td class="text-muted">
                  <% if job.person.position == "" %>
                    <%= job.person.name %>　さん
                  <% else %>
                    <%= job.person.name %><%= job.person.position %>
                  <% end %>
                </td>
                <td class="text-muted"><%= job.type_i18n %></td>
                <td class="text-muted"><%= job.content %></td>
              </tr>
            <% else %>
              <tr>
                <td>
                  <%= job.date %>
                  <%= link_to '完了', users_job_path(job, job: {completed: true}), method: :put, class: "btn btn-sm btn-success" %></td>
                <td>
                  <% if job.person.position == "" %>
                    <%= job.person.name %>　さん
                  <% else %>
                    <%= job.person.name %><%= job.person.position %>
                  <% end %>
                </td>
                <td><%= job.type_i18n %></td>
                <td><%= job.content %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>