config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_in' => 'customers/sessions#new', as: 'new_customer_session'
    post 'customers/sign_in' => 'customers/sessions#create', as: 'customer_session'
    delete 'customers/sign_out' => 'customers/sessions#destroy', as: 'destroy_customer_session'
    get 'customers/sign_up' => 'customers/registrations#new', as: 'new_customer_registration'
    post 'customers' => 'customers/registrations#create', as: 'customer_registration'
    get 'customers/password/new' => 'customers/passwords#new', as: 'new_customer_password'
  end
  

  devise_for :admins

  devise_for :users, skip: :all
  devise_scope :user do
    get 'users/sign_in' => 'users/sessions#new', as: 'new_user_session'
    post 'users/sign_in' => 'users/sessions#create', as: 'user_session'
    delete 'users/sign_out' => 'users/sessions#destroy', as: 'destroy_user_session'
    get 'users/sign_up' => 'users/registrations#new', as: 'new_user_registration'
    post 'users' => 'users/registrations#create', as: 'user_registration'
    get 'users/password/new' => 'users/passwords#new', as: 'new_user_password'
  end
  
  namespace :users do
    get 'homes/top'
    get 'homes/index'
    resources :shipments do
      collection do
        post :invoice
      end
    end
    resources :constructions
    resources :bodies
    resources :companies
    resources :persons
    resources :jobs
    resources :record_pdfs, only: :index
    resources :shippeds
  end

  

  root 'users/homes#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ApplicationRecord
  belongs_to :construction
  has_many :shippeds, dependent: :destroy
  has_many :heads, through: :shippeds
  enum format: {
    ke: 0,
    ko: 1,
    m: 2,
    ryubei: 3,
    ki: 4,
    hon: 5,
    mai: 6,
    ton: 7
  }
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :persons, dependent: :destroy
  belongs_to :user
  has_many :heads, dependent: :destroy
  has_many :construction, dependent: :destroy
end

app/models/construction.rb
class Construction < ApplicationRecord
  belongs_to :user
  has_many :heads, dependent: :destroy
  has_many :bodies, dependent: :destroy
  belongs_to :company
  mount_uploader :image, ImageUploader
  

  def full_address
    delivery_name + "【" + name + "】" + address + "（" + person + "さん）"
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/form.rb
module Form
  def self.table_name_prefix
    'form_'
  end
end

app/models/head.rb
class Head < ApplicationRecord
  belongs_to :user
  belongs_to :construction
  belongs_to :company
  has_many :shippeds, dependent: :destroy
  has_many :bodies, through: :shippeds
  accepts_nested_attributes_for :shippeds, reject_if: :reject_shipped, allow_destroy: true
  def reject_shipped(attributes)
    exists = attributes[:id].present?
    empty = attributes[:quantity].blank?
    attributes.merge!(_destroy: 1) if exists && empty
    !exists && empty
  end
  enum vehicle: {
    h4t: 0,
    h5t: 1,
    h7t: 2,
    h10t: 3,
    h13t: 4,
    traler: 5,
    kogata: 6,
    chugata: 7,
    oogata: 8
  }
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :person
  self.inheritance_column = :_type_disabled
  validates :date, presence: true
  validates :type, presence: true
  enum type: {
    mitsumori: 0,
    syouninirai: 1,
    nouhinyotei: 2,
    ketsuron: 3,
    kuremu: 4,
    tsurikanagu: 5,
    shukin: 6,
    sonota: 7
  }
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :company
  has_many :jobs, dependent: :destroy
end

app/models/shipped.rb
class Shipped < ApplicationRecord
  belongs_to :head
  belongs_to :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :heads, dependent: :destroy
  has_many :constructions, dependent: :destroy
  has_many :companies, dependent: :destroy

  enum department: {
    honten: 0,
    kitakei: 1,
    kennan: 2,
    chikuho: 3,
    kitakyu: 4
  }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: '出荷ソフト',
      title: 'トップページ',
      reverse: true,
      charset: 'utf-8',
      description: 'ご訪問ありがとうございます。出荷ソフトをruby on ralesで作成しました。',
      keywords: 'rails,ruby,プログラミング,bike,coffee',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('kashiwagi_logo.png') }
      ],
      og: {
        site_name: :site, # もしくは site_name: :site
        title: :title, # もしくは title: :title
        description: :description, # もしくは description: :description
        type: 'shipping',
        url: request.original_url,
        image: image_url('kashiwagi_logo.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@fumihisa_y',
      }
    }
  end
end

app/helpers/users/bodies_helper.rb
module Users::BodiesHelper
  def qrcode
    qrcode = RQRCode::QRCode.new(
      if @construction.address == ""
        "https://www.kashiwagi-k.co.jp/"
      else
        @construction.address
      end
    )
    svg = qrcode.as_svg(
      color: "008000",
      shape_rendering: "crispEdges",
      module_size: 4,
      standalone: true,
      use_path: true
    ).html_safe
  end
end

app/helpers/users/companies_helper.rb
module Users::CompaniesHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/jobs_helper.rb
module Users::JobsHelper
end

app/helpers/users/persons_helper.rb
module Users::PersonsHelper
end

app/helpers/users/shippeds_helper.rb
module Users::ShippedsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/shared/_navber.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a href="<%= root_path %>" class="navbar-brand"><%= image_tag 'kashiwagi.png', :size => '150x200' %></a>
      <div class="sign-message">
        <% if user_signed_in? %>
          <div class="sign-in-message">
            Welcome!
            <%= current_user.name %>さん
          </div>
        <% elsif admin_signed_in? %>
          <div class="sign-in-message">ご苦労様！</div>
        <% else %>
          <div class="sign-before">ログインして下さい！</div>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-lavel="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Master
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if admin_signed_in? %>
                <li><a href="<%= users_shipments_path %>" class="dropdown-item">shipmentList</a></li>
                <li><a href="<%#= admins_categories_path %>" class="dropdown-item">Category</a></li>
                <li><a href="<%#= admins_details_path %>" class="dropdown-item">Detail</a></li>
              <% elsif user_signed_in? %>
                <li><a href="<%= users_shipments_path %>" class="dropdown-item">shipmentList</a></li>
                <li><a href="<%#= users_details_path %>" class="dropdown-item">Detail</a></li>
                <li><a href="<%= users_record_pdfs_path(format: "pdf") %>" class="dropdown-item">名刺</a></li>
              <% else %>
                <li><a href="<%= users_record_pdfs_path(format: "pdf") %>" class="dropdown-item">名刺</a></li>
              <% end %>
            </ul>
          </li>
          <% if user_signed_in? || admin_signed_in? || customer_signed_in? %>
            <li class="nav-item">
              <a href="<%= destroy_user_session_path %>" class="nav-link" data-method="delete" tavindex="-1" aria-disabled="true">Logout</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a href="<%= new_user_session_path %>" class="nav-link" tavindex="-1" aria-disabled="true">社員Login</a>
            </li>
          <% end %>
        </ul>
        <%= form_tag(users_companies_path, method: :get) do %>
          <%= text_field_tag('search') %>
          <%= submit_tag("search") %>
        <% end %>
      </div>
    </div>
  </nav>
</header>